### ISSUE TITLE
add .gexf to allowed files

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-assets#12]
https://de.wikipedia.org/wiki/Graph_Exchange_XML_Format

**Comment by zozlak** [comment]
Oh my, something so popular it has a wikipedia page only in German...

Is this something provided by a depositor?

**Comment by zozlak** [comment]
By the way, the filechecker recognizes it as gexf or as a generic xml?

**Comment by zozlak** [comment]
Last but not least historically adding new accepted formats was controlled by @bellerophons-pegasus . I'm not sure what's the procedure at the moment (@sstuhec ?).

**Comment by csae8092** [comment]
> filechecker

```
{"directory":"/data","filename":"relations.gexf","severity":"ERROR","errorType":"File format not accepted","errorMessage":"MIME application/xml: accepted, extension gexf: not accepted"}
```

> popular:

well, its documented https://gexf.net/ ; supported by [Gephi](https://gephi.org/) and by network libraries like [NetworkX](https://networkx.org/documentation/stable/reference/readwrite/gexf.html) 

> provided by depositor

yes, but the depositor is me, so I can rename the file

**Comment by zozlak** [comment]
So you have a few options:

* Make @seta or @bellerophons-pegasus say yes in which case we will merge your pull request and this will make the filechecker to issue only a warning (cause it will still don't like that much a generic application/xml file; still I can deal with it later by hand-tuning the filechecker to recognize the gexf based on the xml content).
* Rename your file to `.xml` which will have same consequences as above but no acceptance is needed from anyone else.
* Serialize your graph in another format which is recognized by the DROID (the file format recognition tool used by the filechecker) and accepter by the ARCHE. Unfortunately quick research indicates DROID sucks at recognizing graph formats listed on the [Gephi supported formats list](https://gephi.org/users/supported-graph-formats/) and I guess when it comes to the ARCHE we currently accept only CSV from that list (and IMHO using a CSV would make it slightly cryptic for reuse). So it doesn't really look like a viable option.

**Comment by bellerophons-pegasus** [comment]
We can safely include the format as accepted because:

* It is an XML-based, aka text-based format. 
* It has a documented specification (also in GitHub: https://github.com/gephi/gexf ). 
* It is known in the fileformats wiki: http://fileformats.archiveteam.org/wiki/GEXF
* Gephi is a widely used software for network analysis

I would not say it is preferred though. There seem to be better options like [GraphML](http://graphml.graphdrawing.org/), [JSON graph](https://jsongraphformat.info/) or [GML (Graph Modelling Language)](https://github.com/GunterMueller/UNI_PASSAU_FMI_Graph_Drawing/blob/master/GML/gml-technical-report.pdf), which are also supported across a larger selection of network analysis software
