### ISSUE TITLE
Adjust file formats list making it easy to determine if a given format is accepted by ARCHE or not

### ISSUE THREAD

**Issue by zozlak** [acdh-oeaw/arche-assets#6]
The repo-file-checker needs a reliable source of information on which formats are accepted by ARCHE and which aren't. Basically the list we show on https://arche.acdh.oeaw.ac.at/browser/formats-filenames-and-metadata but available in a machine-readable format.

The [formats list](https://github.com/acdh-oeaw/arche-assets/blob/master/AcdhArcheAssets/formats.json) provided by this repo seems like a good candidate but I'm not sure how to determine format's status based on it:

* requiring `Long_term_format == yes` seems to be much too strict
* presence on the list seems to be much too weak

Could you (@bellerophons-pegasus) help me out?

**Comment by zozlak** [comment]
Added the `ARCHE_conformance` property to each entry and set it up to be in line with the https://arche.acdh.oeaw.ac.at/browser/formats-filenames-and-metadata .

Also added all formats listed by the https://arche.acdh.oeaw.ac.at/browser/formats-filenames-and-metadata but missing in the `formats.json`.

**Comment by bellerophons-pegasus** [comment]
Thank you and apologies for the delay on my side; Working hours currently aren't enough for me.

The list provided in this repo was indeed intended to be the place to collect basic information about formats. Work on it halted because I was unsure about what information exactly should be included. I am glad it got picked up and would be very happy to discuss it a bit more.
